<?php
/**
 * This file is part of the SysCP project.
 * Copyright (c) 2003-2006 the SysCP Project.
 *
 * For the full copyright and license information, please view the COPYING
 * file that was distributed with this source code. You can also view the
 * COPYING file online at http://files.syscp.org/misc/COPYING.txt
 *
 * @author     Martin Burchert <eremit@syscp.org>
 * @copyright  (c) 2006, the authors
 * @package    Syscp.Framework.API
 * @subpackage Syscp.Handler.Database
 * @license    GPLv2 http://files.syscp.org/misc/COPYING.txt
 * @version    $Id:admin_admins.php 460 2006-04-23 15:07:49 +0200 (So, 23 Apr 2006) martin $
 */

/**
 * @todo Extended documentation here!
 *
 * @author     Martin Burchert <eremit@syscp.org>
 * @copyright  (c) 2006, The Authors
 * @package    Syscp.Framework.API
 * @subpackage Syscp.Handler.Database
 * @see        Syscp_Handler_Database
 */
interface Syscp_Handler_Database_Interface extends Syscp_Handler_Interface
{
	/**
	 * Queries the database with the given query string and returns a result id.
	 *
	 * @param  string    $queryStr    The string to be used as query.
	 * @param  unknown   $unbuffered  Unknown, deprecated?
	 * @return resource  The resource identifier of the result set.
	 */
	public function query($queryStr, $unbuffered=false);
	/**
	 * Returns the next result from the given result identifier.
	 *
	 * @param  resource  $resultID  The resource identifier of the result from which
	 *                              the next array should be returned.
	 * @param  integer   $datatype  Specifies how the resulting array should be returned,
	 *                              see mysql_fetch_array() for a list of possible
	 *                              constants.
	 * @return array     Array in the form as specified in $datatype.
	 */
	public function fetchArray($resultID, $datatype = MYSQL_ASSOC);
	/**
	 * Queries the database with the given query string and returns the first row
	 * of the resultset.
	 *
	 * @param  string   $queryStr  The string to be used as query.
	 * @param  integer  $datatype  Specifies how the resulting array should be returned,
	 *                             see mysql_fetch_array() for a list of possible
	 *                             constants.
	 * @return array    Array in the form as specified in $datatype.
	 */
	public function queryFirst($queryStr, $datatype = MYSQL_ASSOC);
	/**
	 * Closes the connection to the database.
	 *
	 * @return void
	 */
	public function close();
	/**
	 * Returns the number of rows in the given result id.
	 *
	 * @param  resource  $resultID  The resource identifier of the result from which
	 *                              the amount of resulting rows should be returned.
	 * @return integer   Count of rows in the given resource.
	 */
	public function numRows($resultID);
	/**
	 * Returns the autogenerated ID of the previous INSERT operation
	 *
	 * @return integer  The autogenerated ID of the prev. INSERT operation
	 */
	public function insertID();
	/**
	 * Returns the number of affected rows in the previous database operation.
	 *
	 * @return integer  The number of affected rows in the previous operation.
	 */
	public function affectedRows();
}
